import React, { useState, useEffect } from 'react';
import { 
  collection, 
  onSnapshot, 
  query, 
  where, 
  orderBy, 
  addDoc, 
  Timestamp,
  getDocs
} from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { AMC, UserProfile, PartnerProfile, Service } from '../../types';
import { handleFirestoreError, OperationType } from '../../lib/firestore-errors';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Zap, 
  CheckCircle2, 
  Clock, 
  Plus, 
  Search, 
  ChevronRight, 
  Users, 
  Phone, 
  MessageSquare,
  TrendingUp,
  DollarSign,
  AlertCircle,
  X
} from 'lucide-react';

interface PartnerAmcLeadsProps {
  profile: UserProfile;
  partner: PartnerProfile | null;
}

export default function PartnerAmcLeads({ profile, partner }: PartnerAmcLeadsProps) {
  const [myLeads, setMyLeads] = useState<AMC[]>([]);
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [showLeadModal, setShowLeadModal] = useState(false);
  const [loading, setLoading] = useState(false);

  const [formData, setFormData] = useState({
    customerId: '',
    serviceId: '',
    notes: ''
  });

  useEffect(() => {
    if (!partner) return;

    const unsubLeads = onSnapshot(
      query(collection(db, 'amcs'), where('partnerId', '==', profile.uid), orderBy('createdAt', 'desc')),
      (snap) => {
        setMyLeads(snap.docs.map(d => ({ id: d.id, ...d.data() } as AMC)));
      }
    );

    const unsubServices = onSnapshot(collection(db, 'services'), (snap) => {
      setServices(snap.docs.map(d => ({ id: d.id, ...d.data() } as Service)));
    });

    const unsubUsers = onSnapshot(collection(db, 'users'), (snap) => {
      setUsers(snap.docs.map(d => ({ uid: d.id, ...d.data() } as UserProfile)));
    });

    return () => {
      unsubLeads();
      unsubServices();
      unsubUsers();
    };
  }, [profile.uid, partner]);

  const handleSubmitLead = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!partner) return;
    setLoading(true);

    try {
      const selectedService = services.find(s => s.id === formData.serviceId);
      const startDate = new Date();
      const endDate = new Date();
      endDate.setFullYear(endDate.getFullYear() + 1);

      const newLead: Omit<AMC, 'id'> = {
        customerId: formData.customerId,
        partnerId: profile.uid,
        serviceId: formData.serviceId,
        planName: 'Partner Referred Plan',
        description: `AMC Lead generated by partner ${profile.displayName} for ${selectedService?.name}`,
        frequency: 4, // Default
        startDate: Timestamp.fromDate(startDate),
        endDate: Timestamp.fromDate(endDate),
        totalPrice: 4999, // Base policy price
        status: 'pending_payment',
        leadSource: 'partner_lead',
        partnerCommission: 500, // Fixed commission for now
        serviceBookingIds: [],
        scheduledDates: [],
        notes: formData.notes,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now()
      };

      await addDoc(collection(db, 'amcs'), newLead);
      setShowLeadModal(false);
      setFormData({ customerId: '', serviceId: '', notes: '' });
      alert('Lead submitted successfully! You will earn ₹500 commission once the customer pays.');
    } catch (err) {
      handleFirestoreError(err, OperationType.WRITE, 'amcs');
    } finally {
      setLoading(false);
    }
  };

  const pendingLeadsCount = myLeads.filter(l => l.status === 'pending_payment').length;
  const activeLeadsCount = myLeads.filter(l => l.status === 'active').length;
  const totalCommission = myLeads
    .filter(l => l.status === 'active')
    .reduce((acc, curr) => acc + (curr.partnerCommission || 0), 0);

  return (
    <div className="p-6 space-y-8 pb-32">
       {/* Dashboard Header */}
       <div className="bg-slate-900 rounded-[32px] p-8 text-white relative overflow-hidden">
          <div className="relative z-10">
             <p className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-400 mb-2">Lead Partnership</p>
             <h2 className="text-3xl font-black italic mb-4">AMC Profits</h2>
             <p className="text-sm text-white/60 font-medium mb-8 max-w-[200px]">Refer customers for AMC and earn instant commissions.</p>
             
             <div className="flex items-center gap-4">
                <button 
                  onClick={() => setShowLeadModal(true)}
                  className="px-6 py-3 bg-white text-slate-900 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-blue-50 transition-all flex items-center gap-2 shadow-xl shadow-black/20"
                >
                  <Plus size={16} />
                  New Lead
                </button>
             </div>
          </div>
          
          <div className="absolute top-0 right-0 p-8">
             <div className="w-16 h-16 bg-blue-700/20 rounded-3xl flex items-center justify-center text-blue-400">
                <TrendingUp size={32} />
             </div>
          </div>
          <div className="absolute -bottom-10 -right-10 w-48 h-48 bg-blue-700/10 rounded-full blur-3xl" />
       </div>

       {/* Commission Stats */}
       <div className="grid grid-cols-2 gap-4">
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col items-center text-center">
             <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center mb-3">
                <DollarSign size={20} />
             </div>
             <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Earned</p>
             <p className="text-xl font-bold text-slate-900">₹{totalCommission}</p>
          </div>
          <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col items-center text-center">
             <div className="w-10 h-10 bg-blue-50 text-blue-700 rounded-xl flex items-center justify-center mb-3">
                <Zap size={20} />
             </div>
             <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Converted</p>
             <p className="text-xl font-bold text-slate-900">{activeLeadsCount}</p>
          </div>
       </div>

       {/* Leads List */}
       <div className="space-y-4">
          <div className="flex items-center justify-between px-2">
             <h3 className="text-sm font-bold text-slate-900">Lead Pipeline</h3>
             <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{myLeads.length} Total</span>
          </div>

          <div className="space-y-3">
             {myLeads.map(lead => {
               const customer = users.find(u => u.uid === lead.customerId);
               const service = services.find(s => s.id === lead.serviceId);
               return (
                 <div key={lead.id} className="bg-white p-5 rounded-3xl border border-slate-100 shadow-sm flex items-center justify-between group active:scale-[0.98] transition-all">
                    <div className="flex items-center gap-4">
                       <div className="w-10 h-10 bg-slate-50 rounded-xl flex items-center justify-center text-slate-400 shrink-0">
                          {customer?.photoURL ? <img src={customer.photoURL} alt="" className="w-full h-full object-cover rounded-xl" /> : <Users size={20} />}
                       </div>
                       <div>
                          <p className="text-sm font-bold text-slate-900 truncate">{customer?.displayName || 'Unknown'}</p>
                          <p className="text-[10px] font-medium text-slate-400 italic">{service?.name || 'General Maintenance'}</p>
                       </div>
                    </div>
                    <div className="text-right">
                       <p className="text-xs font-black text-emerald-600 mb-1">+₹{lead.partnerCommission}</p>
                       <span className={`text-[8px] font-black uppercase tracking-widest px-2 py-0.5 rounded-full ${
                         lead.status === 'active' ? 'bg-emerald-100 text-emerald-600' : 
                         lead.status === 'pending_payment' ? 'bg-amber-100 text-amber-600' : 
                         'bg-slate-100 text-slate-500'
                       }`}>
                         {lead.status.replace('_', ' ')}
                       </span>
                    </div>
                 </div>
               )
             })}
             
             {myLeads.length === 0 && (
               <div className="p-12 text-center bg-white rounded-3xl border border-dashed border-slate-200">
                  <AlertCircle size={24} className="text-slate-200 mx-auto mb-3" />
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-relaxed">No leads yet.<br/>Start referring to earn!</p>
               </div>
             )}
          </div>
       </div>

       {/* Support Section */}
       <div className="bg-blue-50 p-6 rounded-3xl border border-blue-100 flex items-center gap-4">
          <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-blue-700">
             <Phone size={18} />
          </div>
          <div>
             <p className="text-xs font-bold text-blue-900 mb-0.5">Need help with leads?</p>
             <p className="text-[10px] text-blue-700/70 font-medium">Contact your Relationship Manager</p>
          </div>
       </div>

       {/* Lead Modal */}
       <AnimatePresence>
         {showLeadModal && (
           <div className="fixed inset-0 z-[100] flex items-end justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
             <motion.div
               initial={{ y: '100%' }}
               animate={{ y: 0 }}
               exit={{ y: '100%' }}
               className="bg-white rounded-[32px] w-full max-w-md p-8 pb-12 shadow-2xl overflow-hidden"
             >
                <div className="flex justify-between items-center mb-8">
                   <div>
                      <h3 className="text-xl font-bold italic">Generate AMC Lead</h3>
                      <p className="text-[11px] text-slate-400 font-medium tracking-wide">Submit customer details for conversion</p>
                   </div>
                   <button onClick={() => setShowLeadModal(false)} className="p-2 text-slate-400"><X size={20} /></button>
                </div>

                <form onSubmit={handleSubmitLead} className="space-y-6">
                   <div className="space-y-2">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-2">Select Target Customer</label>
                      <select 
                        required
                        value={formData.customerId}
                        onChange={(e) => setFormData(prev => ({ ...prev, customerId: e.target.value }))}
                        className="w-full h-14 bg-slate-50 border-none rounded-2xl px-6 font-bold text-slate-900 focus:ring-2 focus:ring-blue-700 transition-all appearance-none"
                      >
                         <option value="">Choose customer...</option>
                         {users.filter(u => u.role === 'customer').map(u => (
                           <option key={u.uid} value={u.uid}>{u.displayName}</option>
                         ))}
                      </select>
                   </div>

                   <div className="space-y-2">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-2">Service Category</label>
                      <select 
                        required
                        value={formData.serviceId}
                        onChange={(e) => setFormData(prev => ({ ...prev, serviceId: e.target.value }))}
                        className="w-full h-14 bg-slate-50 border-none rounded-2xl px-6 font-bold text-slate-900 focus:ring-2 focus:ring-blue-700 transition-all appearance-none"
                      >
                         <option value="">Choose service...</option>
                         {services.map(s => (
                           <option key={s.id} value={s.id}>{s.name}</option>
                         ))}
                      </select>
                   </div>

                   <div className="space-y-2">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-2">Additional Requirement Notes</label>
                      <textarea 
                        value={formData.notes}
                        onChange={(e) => setFormData(prev => ({ ...prev, notes: e.target.value }))}
                        placeholder="e.g. AC making noise, prefers morning slots..."
                        className="w-full h-24 bg-slate-50 border-none rounded-2xl p-6 font-medium text-slate-600 focus:ring-2 focus:ring-blue-700 transition-all resize-none shadow-inner"
                      />
                   </div>

                   <button 
                     disabled={loading}
                     type="submit"
                     className="w-full py-5 bg-blue-700 text-white rounded-2xl font-black uppercase tracking-[0.2em] text-[10px] shadow-xl shadow-blue-700/30 active:scale-[0.98] transition-all disabled:opacity-50"
                   >
                     {loading ? 'Submitting...' : 'Confirm Lead Submission'}
                   </button>
                </form>
             </motion.div>
           </div>
         )}
       </AnimatePresence>
    </div>
  );
}
